Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2020-10, with the labels that each got.

#379 Fix import comment bug
  CHANGELOG.md
  instrumentation/net/http/otelhttp/doc.go
Labels: bug

#373 Update google.golang.org/grpc/otelgrpc instrumentation to not accept Tracer
  CHANGELOG.md
  instrumentation/google.golang.org/grpc/otelgrpc/benchmark_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/example/client/main.go
  instrumentation/google.golang.org/grpc/otelgrpc/example/go.sum
  instrumentation/google.golang.org/grpc/otelgrpc/example/server/main.go
  instrumentation/google.golang.org/grpc/otelgrpc/example_interceptor_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/go.mod
  instrumentation/google.golang.org/grpc/otelgrpc/go.sum
  instrumentation/google.golang.org/grpc/otelgrpc/grpc_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/grpctrace.go
  instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go
  instrumentation/google.golang.org/grpc/otelgrpc/interceptor_test.go
Labels: area: instrumentation, priority:p1, release:required-for-ga

#374 Update gopkg.in/macaron.v1/otelmacaron instrumentation to use TracerProvider
  CHANGELOG.md
  instrumentation/gopkg.in/macaron.v1/otelmacaron/config.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/macaron.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/macaron_test.go
Labels: area: instrumentation, priority:p1, release:required-for-ga

#375 [propagator] Add Jaeger propagator
  propagators/jaeger/doc.go
  propagators/jaeger/jaeger_data_test.go
  propagators/jaeger/jaeger_example_test.go
  propagators/jaeger/jaeger_integration_test.go
  propagators/jaeger/jaeger_propagator.go
  propagators/jaeger/jaeger_propagator_test.go
Labels: priority:p2, release:required-for-ga

#400 Update README with Org GA project board
  README.md
Labels: Skip Changelog, documentation

#426 Replace flaky host instrumentation test
  instrumentation/host/host_test.go
Labels: area: testing, bug

#410 [aws detector] Additional Attributes
  detectors/aws/aws.go
  detectors/aws/aws_test.go
Labels: area: detector, priority:p3, release:required-for-ga
