Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2021-01, with the labels that each got.

#498 Add @dashpole as a project Approver
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#514 Merge code coverage output into single file for codecov.io
  .github/workflows/build_and_test.yml
  Makefile
Labels: Skip Changelog

#516 Update CI badge for README
  README.md
Labels: Skip Changelog, documentation

#517 Fix module path for AWS ECS resource detector
  CHANGELOG.md
  detectors/aws/ecs/go.mod
Labels: bug

#557 Upgrade github.com/stretchr/testify from v1.6.1 to v1.7.0
  detectors/aws/ecs/go.mod
  detectors/aws/ecs/go.sum
  detectors/aws/eks/go.mod
  detectors/aws/eks/go.sum
  detectors/aws/go.mod
  detectors/aws/go.sum
  exporters/metric/cortex/example/go.sum
  exporters/metric/cortex/go.mod
  exporters/metric/cortex/go.sum
  exporters/metric/cortex/utils/go.mod
  exporters/metric/cortex/utils/go.sum
  instrumentation/github.com/Shopify/sarama/otelsarama/example/go.sum
  instrumentation/github.com/Shopify/sarama/otelsarama/go.mod
  instrumentation/github.com/Shopify/sarama/otelsarama/go.sum
  instrumentation/github.com/astaxie/beego/otelbeego/example/go.sum
  instrumentation/github.com/astaxie/beego/otelbeego/go.mod
  instrumentation/github.com/astaxie/beego/otelbeego/go.sum
  instrumentation/github.com/bradfitz/gomemcache/memcache/otelmemcache/example/go.sum
  instrumentation/github.com/bradfitz/gomemcache/memcache/otelmemcache/go.mod
  instrumentation/github.com/bradfitz/gomemcache/memcache/otelmemcache/go.sum
  instrumentation/github.com/emicklei/go-restful/otelrestful/example/go.sum
  instrumentation/github.com/emicklei/go-restful/otelrestful/go.mod
  instrumentation/github.com/emicklei/go-restful/otelrestful/go.sum
  instrumentation/github.com/gin-gonic/gin/otelgin/example/go.sum
  instrumentation/github.com/gin-gonic/gin/otelgin/go.mod
  instrumentation/github.com/gin-gonic/gin/otelgin/go.sum
  instrumentation/github.com/gocql/gocql/otelgocql/example/go.sum
  instrumentation/github.com/gocql/gocql/otelgocql/go.mod
  instrumentation/github.com/gocql/gocql/otelgocql/go.sum
  instrumentation/github.com/gorilla/mux/otelmux/example/go.sum
  instrumentation/github.com/gorilla/mux/otelmux/go.mod
  instrumentation/github.com/gorilla/mux/otelmux/go.sum
  instrumentation/github.com/labstack/echo/otelecho/example/go.sum
  instrumentation/github.com/labstack/echo/otelecho/go.mod
  instrumentation/github.com/labstack/echo/otelecho/go.sum
  instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/go.mod
  instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/go.sum
  instrumentation/google.golang.org/grpc/otelgrpc/example/go.sum
  instrumentation/google.golang.org/grpc/otelgrpc/go.mod
  instrumentation/google.golang.org/grpc/otelgrpc/go.sum
  instrumentation/gopkg.in/macaron.v1/otelmacaron/example/go.sum
  instrumentation/gopkg.in/macaron.v1/otelmacaron/go.mod
  instrumentation/gopkg.in/macaron.v1/otelmacaron/go.sum
  instrumentation/host/example/go.sum
  instrumentation/host/go.mod
  instrumentation/host/go.sum
  instrumentation/net/http/httptrace/otelhttptrace/example/go.sum
  instrumentation/net/http/httptrace/otelhttptrace/go.mod
  instrumentation/net/http/httptrace/otelhttptrace/go.sum
  instrumentation/net/http/otelhttp/example/go.sum
  instrumentation/net/http/otelhttp/go.mod
  instrumentation/net/http/otelhttp/go.sum
  propagators/aws/go.mod
  propagators/aws/go.sum
  propagators/go.mod
  propagators/go.sum
  propagators/opencensus/examples/go.sum
Labels: Skip Changelog, go
