Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2022-07, with the labels that each got.

#2561 dependabot updates Wed Jul 6 15:43:39 EDT 2022
  detectors/aws/ec2/go.mod
  detectors/aws/ec2/go.sum
  instrumentation/github.com/aws/aws-lambda-go/otellambda/example/go.mod
  instrumentation/github.com/aws/aws-lambda-go/otellambda/example/go.sum
  instrumentation/github.com/aws/aws-sdk-go-v2/otelaws/example/go.mod
  instrumentation/github.com/aws/aws-sdk-go-v2/otelaws/example/go.sum
  instrumentation/github.com/aws/aws-sdk-go-v2/otelaws/go.mod
  instrumentation/github.com/aws/aws-sdk-go-v2/otelaws/go.sum
  instrumentation/github.com/aws/aws-sdk-go-v2/otelaws/test/go.mod
  instrumentation/github.com/aws/aws-sdk-go-v2/otelaws/test/go.sum
  instrumentation/host/example/go.mod
  instrumentation/host/example/go.sum
  instrumentation/host/go.mod
  instrumentation/host/go.sum
Labels: Skip Changelog

#2563 Add changelog entry for WithPublicEndpointFn
  CHANGELOG.md
Labels: documentation

#2570 Add changelog check github action
  .github/workflows/changelog.yml
Labels: Skip Changelog

#2593 Add TextMapPropagator function to autoprop
  CHANGELOG.md
  propagators/autoprop/example_test.go
  propagators/autoprop/propagator.go
  propagators/autoprop/registry.go
  propagators/autoprop/registry_test.go
Labels: area: propagators

#2609 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation
