Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2023-05, with the labels that each got.

#3804 Add go.work to .gitignore
  .gitignore
Labels: Skip Changelog

#3817 Add semconvutil and use it instead of httpconv and netconv
  Makefile
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/gen.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/httpconv.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/httpconv_test.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/netconv.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/netconv_test.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/restful.go
  instrumentation/github.com/gin-gonic/gin/otelgin/gintrace.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/gen.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/httpconv.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/httpconv_test.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/netconv.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/netconv_test.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/gen.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/httpconv.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/httpconv_test.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/netconv.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/netconv_test.go
  instrumentation/github.com/gorilla/mux/otelmux/mux.go
  instrumentation/github.com/labstack/echo/otelecho/echo.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconvutil/gen.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconvutil/httpconv.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconvutil/httpconv_test.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconvutil/netconv.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconvutil/netconv_test.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/internal/semconvutil/gen.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/internal/semconvutil/httpconv.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/internal/semconvutil/httpconv_test.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/internal/semconvutil/netconv.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/internal/semconvutil/netconv_test.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/macaron.go
  instrumentation/net/http/httptrace/otelhttptrace/go.mod
  instrumentation/net/http/httptrace/otelhttptrace/go.sum
  instrumentation/net/http/httptrace/otelhttptrace/httptrace.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/gen.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/httpconv.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/httpconv_test.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/netconv.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/netconv_test.go
  instrumentation/net/http/otelhttp/handler.go
  instrumentation/net/http/otelhttp/internal/semconvutil/gen.go
  instrumentation/net/http/otelhttp/internal/semconvutil/httpconv.go
  instrumentation/net/http/otelhttp/internal/semconvutil/httpconv_test.go
  instrumentation/net/http/otelhttp/internal/semconvutil/netconv.go
  instrumentation/net/http/otelhttp/internal/semconvutil/netconv_test.go
  instrumentation/net/http/otelhttp/transport.go
  internal/shared/README.md
  internal/shared/semconvutil/httpconv.go.tmpl
  internal/shared/semconvutil/httpconv_test.go.tmpl
  internal/shared/semconvutil/netconv.go.tmpl
  internal/shared/semconvutil/netconv_test.go.tmpl
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: Skip Changelog

#2753 Add autoexport to automatically configure trace exporters
  .github/dependabot.yml
  CHANGELOG.md
  CODEOWNERS
  exporters/autoexport/README.md
  exporters/autoexport/doc.go
  exporters/autoexport/exporter.go
  exporters/autoexport/exporter_test.go
  exporters/autoexport/go.mod
  exporters/autoexport/go.sum
  exporters/autoexport/registry.go
  exporters/autoexport/registry_test.go
  versions.yaml
Labels: area: exporter

#3887 Add @pellared as maintainer
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#3886 Move @Aneurysm9 to approver
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#2964 Add otelhttp.NewMiddleware
  CHANGELOG.md
  instrumentation/net/http/otelhttp/handler.go
Labels: enhancement, area: instrumentation, instrumentation: otelhttp
