Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2023-02, with the labels that each got.

#3188 Add instrgen package to dependabot configuration
  .github/dependabot.yml
Labels: Skip Changelog

#3370 Remove the SDK dependency from `otelmux`
  instrumentation/github.com/gorilla/mux/otelmux/go.mod
  instrumentation/github.com/gorilla/mux/otelmux/go.sum
  instrumentation/github.com/gorilla/mux/otelmux/mux_test.go
  instrumentation/github.com/gorilla/mux/otelmux/test/mux_test.go
Labels: Skip Changelog, instrumentation: otelmux

#3385 Update Damien's affiliation
  CONTRIBUTING.md
Labels: documentation, Skip Changelog

#3045 Add initial Codeowners file
  CODEOWNERS
Labels: Skip Changelog

#3426 Update use of metric `Reader.Collect()`
  instrumentation/github.com/gocql/gocql/otelgocql/example/go.mod
  instrumentation/github.com/gocql/gocql/otelgocql/example/go.sum
  instrumentation/github.com/gocql/gocql/otelgocql/test/go.mod
  instrumentation/github.com/gocql/gocql/otelgocql/test/go.sum
  instrumentation/github.com/gocql/gocql/otelgocql/test/gocql_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/go.mod
  instrumentation/google.golang.org/grpc/otelgrpc/test/go.sum
  instrumentation/google.golang.org/grpc/otelgrpc/test/grpc_test.go
  instrumentation/net/http/otelhttp/test/go.mod
  instrumentation/net/http/otelhttp/test/go.sum
  instrumentation/net/http/otelhttp/test/handler_test.go
Labels: Skip Changelog
