Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2024-03, with the labels that each got.

#5292 Add skeleton of slog bridge
  .github/dependabot.yml
  bridges/otelslog/go.mod
  bridges/otelslog/go.sum
  bridges/otelslog/handler.go
  versions.yaml
Labels: Skip Changelog

#5316 Test NewLogger from slog bridge
  bridges/otelslog/handler_test.go
Labels: Skip Changelog, bridge: slog

#5311 Implement the slog bridge config
  bridges/otelslog/handler.go
  bridges/otelslog/handler_test.go
  bridges/otelslog/version.go
Labels: Skip Changelog

#5327 Test spanRowFormatter, and mark the gosec issue as a false-positive
  zpages/templates.go
  zpages/templates_test.go
Labels: Skip Changelog

#5329 Add multi-logged integration tests to otelslog
  bridges/otelslog/handler_test.go
Labels: Skip Changelog, bridge: slog

#5330 Add benchmarks to otelslog
  bridges/otelslog/handler_test.go
Labels: Skip Changelog, bridge: slog

#5335 Add alpha release of otelslog to next release
  CHANGELOG.md
  versions.yaml
Labels: bridge: slog
