Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2024-10, with the labels that each got.

#6162 dice: Revert otelslog usage
  examples/dice/go.mod
  examples/dice/rolldice.go
Labels: Skip Changelog

#6160 [chore] Add verify_examples.sh
  Makefile
  RELEASING.md
  get_main_pkgs.sh
  tools/go.mod
  tools/go.sum
  tools/tools.go
  verify_examples.sh
Labels: Skip Changelog

#6163 Move @MadVikingGod to Emeritus status
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#6178 Remove toolchain statement from otelgin example
  instrumentation/github.com/gin-gonic/gin/otelgin/example/go.mod
Labels: Skip Changelog

#6161 Use lychee cache
  .github/workflows/links-fail-fast.yml
  .github/workflows/links.yml
Labels: Skip Changelog

#6144 Ignore commit upgrades for otel-go in renovate
  renovate.json
Labels: Skip Changelog

#6179 Add dmathieu as codeowner of the host and runtime instrumentations
  CODEOWNERS
Labels: Skip Changelog

#6184 chore: removing unnecessary comments
  config/config.go
Labels: documentation, Skip Changelog

#6177 Move @hanyuancheung to Emeritus status
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#6194 Add dashpole as an owner of instrumentation/runtime
  CODEOWNERS
Labels: Skip Changelog

#6211 Group golang.org/x dependencies
  renovate.json
Labels: Skip Changelog

#6217 Fix invalid renovate json config
  renovate.json
Labels: Skip Changelog

#6223 Revert "chore(deps): update sigs.k8s.io/json digest to c46165d"
  detectors/aws/eks/go.mod
  detectors/aws/eks/go.sum
Labels: Skip Changelog

#6210 Temporarily consider 429s as success in links check
  .github/workflows/links-fail-fast.yml
  .github/workflows/links.yml
Labels: Skip Changelog

#6224 Run the test compatibility check even if tests failed
  .github/workflows/ci.yml
Labels: Skip Changelog

#6002 feat(instrumentation/http/otelhttp): move client metrics creation into internal semconv package
  instrumentation/net/http/otelhttp/common.go
  instrumentation/net/http/otelhttp/handler.go
  instrumentation/net/http/otelhttp/internal/semconv/env.go
  instrumentation/net/http/otelhttp/internal/semconv/env_test.go
  instrumentation/net/http/otelhttp/internal/semconv/httpconv_test.go
  instrumentation/net/http/otelhttp/internal/semconv/v1.20.0.go
  instrumentation/net/http/otelhttp/internal/semconv/v1.20.0_test.go
  instrumentation/net/http/otelhttp/transport.go
Labels: Skip Changelog

#6229 Revert "chore(deps): update lycheeverse/lychee-action action to v2"
  .github/workflows/links-fail-fast.yml
  .github/workflows/links.yml
Labels: Skip Changelog

#6254 oteslog: Improve transforming slog.KindAny attributes
  CHANGELOG.md
  bridges/otellogrus/hook.go
  bridges/otelslog/convert.go
  bridges/otelslog/convert_test.go
  bridges/otelslog/gen.go
  bridges/otelslog/handler.go
  bridges/otelslog/handler_test.go
  bridges/otelzap/core.go
Labels: enhancement, bridge: slog

#6253 otelslog: Add WithSource option
  CHANGELOG.md
  bridges/otelslog/go.mod
  bridges/otelslog/handler.go
  bridges/otelslog/handler_test.go
Labels: enhancement, bridge: slog

#6206 otellogr: Implement LevelSeverity, Enabled
  bridges/otellogr/example_test.go
  bridges/otellogr/logsink.go
  bridges/otellogr/logsink_test.go
Labels: enhancement, Skip Changelog, bridge: logr

#6279 Add Cheng-Zhen as a triager
  CONTRIBUTING.md
Labels: Skip Changelog
