Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2024-01, with the labels that each got.

#4773 otelgrpc: Remove code that has no effects in stats handlers
  instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go
Labels: Skip Changelog

#4803 Bump detector semconv to v1.24.0
  CHANGELOG.md
  detectors/aws/ec2/ec2.go
  detectors/aws/ec2/ec2_test.go
  detectors/aws/ec2/go.mod
  detectors/aws/ec2/go.sum
  detectors/aws/ecs/ecs.go
  detectors/aws/ecs/ecs_test.go
  detectors/aws/ecs/go.mod
  detectors/aws/ecs/go.sum
  detectors/aws/ecs/test/ecs_test.go
  detectors/aws/eks/detector.go
  detectors/aws/eks/detector_test.go
  detectors/aws/eks/go.mod
  detectors/aws/eks/go.sum
  detectors/aws/lambda/detector.go
  detectors/aws/lambda/detector_test.go
  detectors/aws/lambda/go.mod
  detectors/aws/lambda/go.sum
  detectors/gcp/cloud-function.go
  detectors/gcp/cloud-function_test.go
  detectors/gcp/cloud-run.go
  detectors/gcp/detector.go
  detectors/gcp/detector_test.go
  detectors/gcp/gce.go
  detectors/gcp/gke.go
  detectors/gcp/go.mod
  detectors/gcp/go.sum
  instrumentation/github.com/aws/aws-lambda-go/otellambda/example/go.mod
  instrumentation/github.com/aws/aws-lambda-go/otellambda/example/go.sum
  instrumentation/github.com/aws/aws-lambda-go/otellambda/test/go.mod
  instrumentation/github.com/aws/aws-lambda-go/otellambda/test/go.sum
  instrumentation/github.com/aws/aws-lambda-go/otellambda/test/lambda_test.go
  instrumentation/github.com/aws/aws-lambda-go/otellambda/xrayconfig/go.mod
  instrumentation/github.com/aws/aws-lambda-go/otellambda/xrayconfig/go.sum
Labels: area: detector

#4705 otelgrpc: Remove withoutContext
  instrumentation/google.golang.org/grpc/otelgrpc/example/go.mod
  instrumentation/google.golang.org/grpc/otelgrpc/example/go.sum
  instrumentation/google.golang.org/grpc/otelgrpc/go.mod
  instrumentation/google.golang.org/grpc/otelgrpc/go.sum
  instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/go.mod
  instrumentation/google.golang.org/grpc/otelgrpc/test/go.sum
  propagators/opencensus/examples/go.mod
  propagators/opencensus/examples/go.sum
Labels: Skip Changelog

#4824 config: refactor resource code
  config/config.go
  config/resource.go
  config/resource_test.go
Labels: Skip Changelog

#4822 Add David Ashpole as a maintainer
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#4801 config: Add codeowners
  CODEOWNERS
Labels: Skip Changelog

#4831 docs: spell out unpacking OTEL_RESOURCE_ATTRIBUTES
  detectors/gcp/README.md
Labels: documentation, Skip Changelog

#4704 Prometheus bridge: Add tests to verify that start timestamps are working correctly
  bridges/prometheus/doc.go
  bridges/prometheus/producer_test.go
Labels: Skip Changelog

#4875 [otelgrpc] Do not panic for nil instruments
  CHANGELOG.md
  instrumentation/google.golang.org/grpc/otelgrpc/config.go
  instrumentation/google.golang.org/grpc/otelgrpc/config_test.go
Labels: instrumentation: otelgrpc
