Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2024-06, with the labels that each got.

#5707 otelzap: Allow context injection via fields
  bridges/otelzap/core.go
  bridges/otelzap/core_test.go
Labels: Skip Changelog

#5735 Bump Go version used in CI
  .github/workflows/ci.yml
Labels: Skip Changelog

#5747 Prepare for migration to new runtime metrics
  CHANGELOG.md
  instrumentation/runtime/go.mod
  instrumentation/runtime/go.sum
  instrumentation/runtime/internal/deprecatedruntime/doc.go
  instrumentation/runtime/internal/deprecatedruntime/runtime.go
  instrumentation/runtime/internal/x/README.md
  instrumentation/runtime/internal/x/x.go
  instrumentation/runtime/internal/x/x_test.go
  instrumentation/runtime/runtime.go
Labels: enhancement, instrumentation: runtime

#5401 HTTP Semconv migration Part3 Server - v1.24.0 support
  instrumentation/net/http/otelhttp/internal/semconv/env.go
  instrumentation/net/http/otelhttp/internal/semconv/util.go
  instrumentation/net/http/otelhttp/internal/semconv/v1.20.0.go
  instrumentation/net/http/otelhttp/internal/semconv/v1.24.0.go
  instrumentation/net/http/otelhttp/internal/semconv/v1.24.0_test.go
Labels: Skip Changelog

#5767 Fix broken link
  instrumentation/runtime/internal/x/README.md
Labels: Skip Changelog

#5721 otelzap: Implement namespace method
  bridges/otelzap/core.go
  bridges/otelzap/encoder.go
  bridges/otelzap/encoder_test.go
Labels: Skip Changelog

#5778 Update project approvers
  CONTRIBUTING.md
Labels: Skip Changelog

#5794 Do not fail CI on codecov create report
  .github/workflows/ci.yml
Labels: Skip Changelog

#5789 Remove pdata dependency and use proto-go instead
  exporters/autoexport/go.mod
  exporters/autoexport/go.sum
  exporters/autoexport/metrics_test.go
Labels: Skip Changelog

#5797 otelzap: Add severity text to log record
  bridges/otelzap/core.go
  bridges/otelzap/core_test.go
Labels: Skip Changelog

#5784 otelzap: Add Benchmarks
  bridges/otelzap/core.go
  bridges/otelzap/core_test.go
Labels: Skip Changelog

#5802 Add unconvert linter
  .golangci.yml
  bridges/otelzap/core_test.go
  bridges/otelzap/encoder.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/netconv.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/netconv.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/netconv.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconvutil/netconv.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/internal/semconvutil/netconv.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/netconv.go
  instrumentation/net/http/otelhttp/internal/semconvutil/netconv.go
  internal/shared/semconvutil/netconv.go.tmpl
  propagators/b3/b3_propagator.go
Labels: Skip Changelog

#5803 Add unparam linter
  .golangci.yml
  detectors/gcp/cloud-function.go
  detectors/gcp/cloud-run.go
  instrgen/lib/context_propagation.go
  instrumentation/github.com/gorilla/mux/otelmux/test/mux_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/grpc_test.go
  instrumentation/runtime/internal/x/x_test.go
  samplers/aws/xray/fallback_sampler.go
  samplers/aws/xray/internal/client.go
  samplers/aws/xray/internal/manifest.go
  samplers/aws/xray/internal/manifest_test.go
  samplers/aws/xray/internal/reservoir.go
Labels: Skip Changelog

#5801 Add tenv linter
  .golangci.yml
Labels: Skip Changelog

#5805 otelzap: add testable example and package documentation
  bridges/otelzap/README.md
  bridges/otelzap/example_test.go
Labels: Skip Changelog

#5804 Add errorlint linter
  .golangci.yml
  config/metric.go
  detectors/aws/ec2/ec2.go
  detectors/gcp/cloud-function_test.go
  detectors/gcp/gce.go
  exporters/autoexport/metrics.go
  instrumentation/google.golang.org/grpc/otelgrpc/example/client/main.go
  instrumentation/google.golang.org/grpc/otelgrpc/example/server/main.go
  instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go
  instrumentation/google.golang.org/grpc/otelgrpc/internal/test/test_utils.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/grpc_stats_handler_test.go
  instrumentation/net/http/otelhttp/internal/semconv/v1.20.0.go
Labels: Skip Changelog

#5809 Rename BaggageKeyPredicate to Filter
  CHANGELOG.md
  processors/baggage/baggagetrace/processor.go
Labels: processor: baggage

#5810 Return `SpanProcessor` ptr not `trace.SpanProcessor` from `baggagetrace.New`
  CHANGELOG.md
  processors/baggage/baggagetrace/processor.go
Labels: processor: baggage

#5811 Do not panic for empty `baggagetrace.SpanProcessor`
  CHANGELOG.md
  processors/baggage/baggagetrace/processor.go
  processors/baggage/baggagetrace/processor_test.go
Labels: processor: baggage

#5812 Do not alias baggage import
  processors/baggage/baggagetrace/processor.go
  processors/baggage/baggagetrace/processor_test.go
Labels: Skip Changelog, processor: baggage

#5813 Change BaggageKeyPredicate to filter baggage Members
  CHANGELOG.md
  processors/baggage/baggagetrace/example_test.go
  processors/baggage/baggagetrace/processor.go
  processors/baggage/baggagetrace/processor_test.go
Labels: processor: baggage

#5819 Add comment to the safety of the uint8 cast
  samplers/probability/consistent/tracestate.go
Labels: documentation, Skip Changelog
