Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2024-04, with the labels that each got.

#5355 otelslog: Add example
  bridges/otelslog/exampe_test.go
Labels: Skip Changelog, bridge: slog

#5358 chore: fix two otelslog typos
  bridges/otelslog/example_test.go
  bridges/otelslog/handler.go
Labels: documentation, Skip Changelog

#5364 Add benchmarks for the prometheus bridge
  bridges/prometheus/BENCHMARKS.md
  bridges/prometheus/doc.go
Labels: Skip Changelog

#5333 HTTP Semconv migration Part1 Server - v1.20.0 support
  instrumentation/net/http/otelhttp/handler.go
  instrumentation/net/http/otelhttp/internal/semconv/bench_test.go
  instrumentation/net/http/otelhttp/internal/semconv/common_test.go
  instrumentation/net/http/otelhttp/internal/semconv/env.go
  instrumentation/net/http/otelhttp/internal/semconv/util.go
  instrumentation/net/http/otelhttp/internal/semconv/util_test.go
  instrumentation/net/http/otelhttp/internal/semconv/v1.20.0.go
  instrumentation/net/http/otelhttp/internal/semconv/v1.20.0_test.go
Labels: Skip Changelog
