Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2024-07, with the labels that each got.

#5841 Revert toolchain addition to autoexport
  exporters/autoexport/go.mod
Labels: Skip Changelog

#5845 Upgrade Go versions in CI
  .github/workflows/ci.yml
Labels: Skip Changelog

#5838 Add @XSAM and @dmathieu as repository maintainers
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#5842 Remove redundant otelhttp allocation
  instrumentation/net/http/otelhttp/handler.go
  instrumentation/net/http/otelhttp/transport.go
Labels: Skip Changelog, instrumentation: otelhttp

#5852 Use logtest.AssertRecordEqual in logrus bridge
  bridges/otellogrus/hook_test.go
Labels: Skip Changelog

#5773 HTTP Semconv migration Part1 Client - v1.24.0 support
  instrumentation/net/http/otelhttp/internal/semconv/common_test.go
  instrumentation/net/http/otelhttp/internal/semconv/env.go
  instrumentation/net/http/otelhttp/internal/semconv/v1.20.0.go
  instrumentation/net/http/otelhttp/internal/semconv/v1.20.0_test.go
  instrumentation/net/http/otelhttp/transport.go
Labels: Skip Changelog

#5878 otelslog: Remove the pooled buffer
  bridges/otelslog/handler.go
Labels: Skip Changelog, bridge: slog

#5782 Add skeleton for zerolog bridge
  bridges/otelzerolog/example_test.go
  bridges/otelzerolog/go.mod
  bridges/otelzerolog/go.sum
  bridges/otelzerolog/hook.go
  bridges/otelzerolog/hook_test.go
  versions.yaml
Labels: Skip Changelog

#5897 otelzap: Add test for passing context
  bridges/otelzap/core_test.go
Labels: Skip Changelog

#5895 otelzap: remove TODO comments for using pooled objects
  bridges/otelzap/core.go
  bridges/otelzap/encoder.go
Labels: Skip Changelog

#5896 otezap: Add support for zap named loggers
  bridges/otelzap/core.go
  bridges/otelzap/core_test.go
Labels: Skip Changelog

#5905 added codeowners for zerolog bridge
  CODEOWNERS
Labels: Skip Changelog

#5906 Protect released changelog in CI
  .github/workflows/protect-released-changelog.yml
  CHANGELOG.md
  RELEASING.md
  tools/verify_released_changelog.sh
Labels: Skip Changelog, Unlock Released Changelog

#5780 Implement new runtime metrics
  CHANGELOG.md
  instrumentation/runtime/doc.go
  instrumentation/runtime/options.go
  instrumentation/runtime/options_test.go
  instrumentation/runtime/runtime.go
  instrumentation/runtime/runtime_test.go
  instrumentation/runtime/test/go.mod
  instrumentation/runtime/test/go.sum
  instrumentation/runtime/test/runtime_test.go
Labels: instrumentation: runtime

#5917 otelzap: Add package documentation
  bridges/otelzap/core.go
  bridges/otelzap/example_test.go
Labels: Skip Changelog

#5922 otellogrus: Fix package documentation
  bridges/otellogrus/hook.go
Labels: Skip Changelog, bridge: logrus

#5918 zerolog: Hook implementation
  bridges/otelzerolog/hook.go
  bridges/otelzerolog/hook_test.go
Labels: Skip Changelog

#5925 otelzerolog: Add benchmark
  bridges/otelzerolog/hook_test.go
Labels: Skip Changelog

#5933 Fix otelzap docs
  bridges/otelzap/core.go
Labels: bug, Skip Changelog, bridge: zap

#5930 otelzerolog: Add otelzerolog under experimental bridge
  CHANGELOG.md
  bridges/otelzerolog/hook.go
  versions.yaml
Labels: enhancement, bridge: zerolog
