Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2024-05, with the labels that each got.

#5434 Add update-all-otel-deps target in Makefile
  Makefile
Labels: Skip Changelog

#5484 otelslog: Refine TestNewHandlerConfiguration
  bridges/otelslog/handler_test.go
Labels: Skip Changelog

#5526 Add dependencies label to renovate PRs
  renovate.json
Labels: Skip Changelog

#5449 otelzap: Add skeleton and config options
  .github/dependabot.yml
  CODEOWNERS
  bridges/otelzap/core.go
  bridges/otelzap/core_test.go
  bridges/otelzap/go.mod
  bridges/otelzap/go.sum
  bridges/otelzap/version.go
  versions.yaml
Labels: Skip Changelog

#4832 config: add support for additional properties in resource
  CHANGELOG.md
  config/generated_config.go
  config/resource.go
  config/resource_test.go
  config/trace_test.go
Labels: area: config

#5533 Move Aneurysm9 to emeritus status
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#5539 otelzap: Basic implementation of Core.Write
  bridges/otelzap/core.go
  bridges/otelzap/core_test.go
Labels: Skip Changelog

#5577 Remove dependabot version updates
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/create-dependabot-pr.yml
  .github/workflows/dependabot.yml
  .github/workflows/scripts/dependabot-pr.sh
  Makefile
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: Skip Changelog

#5566 otelzap: Skeleton for zap encoder
  bridges/otelzap/encoder.go
Labels: Skip Changelog

#5596 Add dashpole as a codeowner for otelrestful
  CODEOWNERS
Labels: Skip Changelog

#5595 otelzap: Implement methods on objectEncoder
  bridges/otelzap/encoder.go
  bridges/otelzap/encoder_test.go
Labels: Skip Changelog

#5594 otelzap: Implement Enabled method
  bridges/otelzap/core.go
  bridges/otelzap/core_test.go
Labels: Skip Changelog

#5588 otelslog: Replace WithInstrumentationScope with options and and argument
  CHANGELOG.md
  bridges/otelslog/example_test.go
  bridges/otelslog/go.mod
  bridges/otelslog/go.sum
  bridges/otelslog/handler.go
  bridges/otelslog/handler_test.go
  bridges/otelslog/version.go
Labels: bridge: slog

#5604 otelzap: remove dependency on logs sdk
  bridges/otelzap/core.go
  bridges/otelzap/core_test.go
  bridges/otelzap/go.mod
  bridges/otelzap/go.sum
  bridges/otelzap/version.go
Labels: Skip Changelog, bridge: zap

#5606 Replace WithInstrumentationScope with options and and argument
  bridges/otellogrus/example_test.go
  bridges/otellogrus/go.mod
  bridges/otellogrus/go.sum
  bridges/otellogrus/hook.go
  bridges/otellogrus/hook_test.go
  bridges/otellogrus/version.go
Labels: Skip Changelog, bridge: logrus

#5602 otelzap: Implement methods on `objectEncoder`
  bridges/otelzap/encoder.go
  bridges/otelzap/encoder_test.go
Labels: Skip Changelog, bridge: zap

#5609 otelzap: Implement Uint methods on encoder
  bridges/otelzap/encoder.go
  bridges/otelzap/encoder_test.go
Labels: Skip Changelog

#5611 otelzap: Add skeleton for array encoder
  bridges/otelzap/core.go
  bridges/otelzap/encoder.go
Labels: Skip Changelog

#5598 Add deprecation notice to otelmongo
  CHANGELOG.md
  instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/doc.go
  instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/go.mod
  instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/test/mongo_test.go
Labels: instrumentation: otelmongo, abandoned

#5632 otelzap: Implement methods on arrayEncoder
  bridges/otelzap/encoder.go
  bridges/otelzap/encoder_test.go
Labels: Skip Changelog

#5639 Deprecate otelmongo/test
  instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/test/doc.go
  instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/test/go.mod
Labels: Skip Changelog

#5652 otelzap: Implement methods on `arrayEncoder`
  bridges/otelzap/encoder.go
  bridges/otelzap/encoder_test.go
Labels: Skip Changelog

#5676 Use passthrough resolver when bufnet is used
  instrumentation/google.golang.org/grpc/otelgrpc/benchmark_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/grpc_test.go
Labels: Skip Changelog, instrumentation: otelgrpc

#5680 Add link to codeowners policy in codeowners file
  CODEOWNERS
Labels: Skip Changelog

#5686 fix: OTEL_TRACES_EXPORTER typo
  exporters/autoexport/spans.go
Labels: documentation, Skip Changelog

#5681 Add otelhttp Handler.ServeHTTP and Transport.RoundTrip benchmarks
  instrumentation/net/http/otelhttp/test/handler_test.go
  instrumentation/net/http/otelhttp/test/transport_test.go
Labels: Skip Changelog

#5683 Add codespell to CI
  .codespellignore
  .codespellrc
  .github/ISSUE_TEMPLATE/owner.md
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/codespell.yml
  .gitignore
  .golangci.yml
  CONTRIBUTING.md
  Makefile
  RELEASING.md
  config/metric.go
  detectors/aws/ecs/ecs_test.go
  doc.go
  exporters/autoexport/metrics.go
  exporters/autoexport/spans.go
  instrgen/lib/analysis.go
  instrumentation/github.com/aws/aws-lambda-go/otellambda/README.md
  instrumentation/github.com/aws/aws-lambda-go/otellambda/xrayconfig/mock_collector_test.go
  instrumentation/github.com/aws/aws-sdk-go-v2/otelaws/test/version.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/config.go
  instrumentation/github.com/gorilla/mux/otelmux/config.go
  instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/doc.go
  instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/mongo.go
  instrumentation/google.golang.org/grpc/otelgrpc/config.go
  instrumentation/net/http/otelhttp/client.go
  instrumentation/net/http/otelhttp/config.go
  instrumentation/runtime/runtime.go
  propagators/autoprop/registry_test.go
  propagators/b3/b3_data_test.go
  renovate.json
  requirements.txt
  samplers/aws/xray/internal/reservoir_test.go
Labels: Skip Changelog

#5653 otelzap: Implement With method
  bridges/otelzap/core.go
  bridges/otelzap/core_test.go
Labels: Skip Changelog

#5665 otelzap: Implement methods on encoder
  bridges/otelzap/core.go
  bridges/otelzap/encoder.go
  bridges/otelzap/encoder_test.go
Labels: Skip Changelog
