Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2024-02, with the labels that each got.

#4878 Remove unused portions of the internal semconvutil
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/httpconv.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/httpconv_test.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/netconv.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/netconv_test.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/httpconv.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/httpconv_test.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/netconv.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/netconv_test.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/httpconv.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/httpconv_test.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/netconv.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/netconv_test.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconvutil/httpconv.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconvutil/httpconv_test.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconvutil/netconv.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconvutil/netconv_test.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/internal/semconvutil/httpconv.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/internal/semconvutil/httpconv_test.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/internal/semconvutil/netconv.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/internal/semconvutil/netconv_test.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/httpconv.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/httpconv_test.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/netconv.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/netconv_test.go
  instrumentation/net/http/otelhttp/internal/semconvutil/httpconv.go
  instrumentation/net/http/otelhttp/internal/semconvutil/httpconv_test.go
  instrumentation/net/http/otelhttp/internal/semconvutil/netconv.go
  instrumentation/net/http/otelhttp/internal/semconvutil/netconv_test.go
  internal/shared/semconvutil/httpconv.go.tmpl
  internal/shared/semconvutil/httpconv_test.go.tmpl
  internal/shared/semconvutil/netconv.go.tmpl
  internal/shared/semconvutil/netconv_test.go.tmpl
Labels: Skip Changelog

#4707 otelhttp: client metrics
  CHANGELOG.md
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/httpconv.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/httpconv_test.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/httpconv.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/httpconv_test.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/httpconv.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/httpconv_test.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconvutil/httpconv.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconvutil/httpconv_test.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/internal/semconvutil/httpconv.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/internal/semconvutil/httpconv_test.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/httpconv.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/httpconv_test.go
  instrumentation/net/http/otelhttp/common.go
  instrumentation/net/http/otelhttp/handler.go
  instrumentation/net/http/otelhttp/internal/semconvutil/httpconv.go
  instrumentation/net/http/otelhttp/internal/semconvutil/httpconv_test.go
  instrumentation/net/http/otelhttp/test/handler_test.go
  instrumentation/net/http/otelhttp/test/transport_test.go
  instrumentation/net/http/otelhttp/transport.go
  instrumentation/net/http/otelhttp/transport_test.go
  internal/shared/semconvutil/httpconv.go.tmpl
  internal/shared/semconvutil/httpconv_test.go.tmpl
Labels: instrumentation: otelhttp

#4898 Update changelog to note changes to http request/response size metric names
  CHANGELOG.md
Labels: documentation, Skip Changelog, instrumentation: otelhttp

#4897 fork a subset of google.golang.org/grpc/interop to otelgrpc
  instrumentation/google.golang.org/grpc/otelgrpc/benchmark_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/example/go.sum
  instrumentation/google.golang.org/grpc/otelgrpc/go.mod
  instrumentation/google.golang.org/grpc/otelgrpc/go.sum
  instrumentation/google.golang.org/grpc/otelgrpc/internal/test/test_utils.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/go.mod
  instrumentation/google.golang.org/grpc/otelgrpc/test/go.sum
  instrumentation/google.golang.org/grpc/otelgrpc/test/grpc_stats_handler_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/grpc_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/interceptor_test.go
  propagators/opencensus/examples/go.mod
  propagators/opencensus/examples/go.sum
Labels: Skip Changelog, instrumentation: otelgrpc

#5085 Add package comment to otelgrpc/internal/test
  instrumentation/google.golang.org/grpc/otelgrpc/internal/test/test_utils.go
Labels: Skip Changelog, instrumentation: otelgrpc

#4799 Fix httpconv changes in docs from semconv 1.17 to 1.20
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/httpconv.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/httpconv.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/httpconv.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconvutil/httpconv.go
  instrumentation/gopkg.in/macaron.v1/otelmacaron/internal/semconvutil/httpconv.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/httpconv.go
  instrumentation/net/http/otelhttp/internal/semconvutil/httpconv.go
  internal/shared/semconvutil/httpconv.go.tmpl
Labels: documentation, Skip Changelog

#5089 Add support for summary metrics in the prometheus bridge
  CHANGELOG.md
  bridges/prometheus/doc.go
  bridges/prometheus/producer.go
  bridges/prometheus/producer_test.go
Labels: enhancement

#5093 Support exponential histograms in the prometheus bridge
  CHANGELOG.md
  bridges/prometheus/doc.go
  bridges/prometheus/producer.go
  bridges/prometheus/producer_test.go
Labels: enhancement

#5135 Fix broken link to the FAAS semantic conventions
  detectors/aws/lambda/README.md
Labels: documentation, Skip Changelog

#5161 Remove experimental-metrics module set
  versions.yaml
Labels: Skip Changelog
