Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2025-06, with the labels that each got.

#7415 Remove changelog entry for xray propagator.inject
  CHANGELOG.md
Labels: Skip Changelog

#7380 otelzap: refactor Core tests
  bridges/otelzap/core_test.go
Labels: Skip Changelog, bridge: zap

#7414 otellogrus: refactor tests
  bridges/otellogrus/hook_test.go
Labels: Skip Changelog, bridge: logrus

#7416 otellogr: refactor tests
  bridges/otellogr/logsink_test.go
Labels: Skip Changelog, bridge: logr

#7366 Fix verify_examples.sh to work from tools directory
  tools/verify_examples.sh
Labels: Skip Changelog

#7425 Remove internal/utils package from jaegersampler
  samplers/jaegerremote/internal/ratelimiter/rate_limiter.go
  samplers/jaegerremote/internal/ratelimiter/rate_limiter_test.go
  samplers/jaegerremote/internal/testutils/http_json.go
  samplers/jaegerremote/internal/testutils/http_json_test.go
  samplers/jaegerremote/internal/testutils/mock_agent_test.go
  samplers/jaegerremote/sampler.go
Labels: Skip Changelog

#7449 Remove otelgrpc/test module
  instrumentation/google.golang.org/grpc/otelgrpc/go.mod
  instrumentation/google.golang.org/grpc/otelgrpc/grpc_stats_handler_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/grpc_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/interceptor_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/stats_handlertest_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/doc.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/go.mod
  instrumentation/google.golang.org/grpc/otelgrpc/test/go.sum
  instrumentation/google.golang.org/grpc/otelgrpc/test/version.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/version_test.go
  versions.yaml
Labels: Skip Changelog

#7448 Remove otelmux/test module
  instrumentation/github.com/gorilla/mux/otelmux/muxtest_test.go
  instrumentation/github.com/gorilla/mux/otelmux/test/doc.go
  instrumentation/github.com/gorilla/mux/otelmux/test/go.mod
  instrumentation/github.com/gorilla/mux/otelmux/test/go.sum
  instrumentation/github.com/gorilla/mux/otelmux/test/version.go
  instrumentation/github.com/gorilla/mux/otelmux/test/version_test.go
  versions.yaml
Labels: Skip Changelog

#7450 Remove otelgin/test module
  instrumentation/github.com/gin-gonic/gin/otelgin/gin_test.go
  instrumentation/github.com/gin-gonic/gin/otelgin/go.mod
  instrumentation/github.com/gin-gonic/gin/otelgin/go.sum
  instrumentation/github.com/gin-gonic/gin/otelgin/test/doc.go
  instrumentation/github.com/gin-gonic/gin/otelgin/test/go.mod
  instrumentation/github.com/gin-gonic/gin/otelgin/test/go.sum
  instrumentation/github.com/gin-gonic/gin/otelgin/test/version.go
  instrumentation/github.com/gin-gonic/gin/otelgin/test/version_test.go
  versions.yaml
Labels: Skip Changelog

#7454 Remove otellambda/test module
  instrumentation/github.com/aws/aws-lambda-go/otellambda/example/go.sum
  instrumentation/github.com/aws/aws-lambda-go/otellambda/go.mod
  instrumentation/github.com/aws/aws-lambda-go/otellambda/go.sum
  instrumentation/github.com/aws/aws-lambda-go/otellambda/lambdatest_test.go
  instrumentation/github.com/aws/aws-lambda-go/otellambda/test/doc.go
  instrumentation/github.com/aws/aws-lambda-go/otellambda/test/go.mod
  instrumentation/github.com/aws/aws-lambda-go/otellambda/test/go.sum
  versions.yaml
Labels: Skip Changelog

#7437 Only check links in changed files for fail-fast
  .github/workflows/links-fail-fast.yml
Labels: Skip Changelog

#7467 chore: Change "New Instrumentation" into "New Component"
  .github/ISSUE_TEMPLATE/component-request.md
  CONTRIBUTING.md
  instrumentation/README.md
Labels: Skip Changelog

#7485 Fix the v1.36.0 release link
  CHANGELOG.md
Labels: Unlock Released Changelog

#7495 bridges/otelslog: fix spelling error
  bridges/otelslog/handler_test.go
Labels: documentation, Skip Changelog

#7469 otelconf: skip flaky exporter tests on windows
  .lycheeignore
  otelconf/v0.3.0/log_test.go
  otelconf/v0.3.0/metric_test.go
  otelconf/v0.3.0/trace_test.go
Labels: Skip Changelog

#7533 config: replace sigs.k8s.io/yaml with go.yaml.in/yaml
  instrumentation/github.com/gorilla/mux/otelmux/go.mod
  otelconf/go.mod
  otelconf/go.sum
  otelconf/v0.2.0/config.go
  otelconf/v0.3.0/config.go
Labels: Skip Changelog, area: file-config
