Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2025-02, with the labels that each got.

#6746 Close stale issues and PRs after 2 years of inactivity
  .github/workflows/close-stale.yml
Labels: Skip Changelog

#6763 Remove otelhttp/test module
  .golangci.yml
  instrumentation/github.com/aws/aws-lambda-go/otellambda/example/go.sum
  instrumentation/net/http/httptrace/otelhttptrace/example/go.sum
  instrumentation/net/http/httptrace/otelhttptrace/go.sum
  instrumentation/net/http/otelhttp/client_test.go
  instrumentation/net/http/otelhttp/config_test.go
  instrumentation/net/http/otelhttp/go.mod
  instrumentation/net/http/otelhttp/go.sum
  instrumentation/net/http/otelhttp/handler_test.go
  instrumentation/net/http/otelhttp/test/doc.go
  instrumentation/net/http/otelhttp/test/go.mod
  instrumentation/net/http/otelhttp/test/go.sum
  instrumentation/net/http/otelhttp/test/handler_test.go
  instrumentation/net/http/otelhttp/test/transport_test.go
  instrumentation/net/http/otelhttp/test/version.go
  instrumentation/net/http/otelhttp/test/version_test.go
  instrumentation/net/http/otelhttp/transport_test.go
  versions.yaml
Labels: Skip Changelog

#6786 chore(otelgin): rename files for improved clarity and consistency
  instrumentation/github.com/gin-gonic/gin/otelgin/config.go
  instrumentation/github.com/gin-gonic/gin/otelgin/gin.go
  instrumentation/github.com/gin-gonic/gin/otelgin/test/gin_test.go
Labels: Skip Changelog

#6815 [config] Allow prometheus to configure IPv6 by using the standard net host port joining
  CHANGELOG.md
  config/v0.2.0/metric.go
  config/v0.2.0/metric_test.go
  config/v0.3.0/metric.go
  config/v0.3.0/metric_test.go
Labels: area: file-config

#6833 minsev: Update to use sdk/log.FilterProcessor
  processors/minsev/example_test.go
  processors/minsev/go.mod
  processors/minsev/go.sum
  processors/minsev/minsev.go
  processors/minsev/minsev_test.go
  processors/minsev/severity_test.go
Labels: enhancement, Skip Changelog
