Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2025-03, with the labels that each got.

#6870 otelslog, otelzap: align with code attributes semantic conventions
  CHANGELOG.md
  bridges/otelslog/handler.go
  bridges/otelslog/handler_test.go
  bridges/otelzap/core.go
  bridges/otelzap/core_test.go
Labels: bridge: slog, bridge: zap

#6887 fix OTEL_HTTP_CLIENT_COMPATIBILITY_MODE to OTEL_SEMCONV_STABILITY_OPT_IN in the changelog
  CHANGELOG.md
Labels: Skip Changelog, Unlock Released Changelog

#6906 Add akats7 to triagers
  CONTRIBUTING.md
Labels: Skip Changelog

#6943 Fix close stale value to be relative
  .github/workflows/close-stale.yml
Labels: Skip Changelog

#7001 Rename config to otelconf in codeowners file
  CODEOWNERS
Labels: Skip Changelog
