Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2025-08, with the labels that each got.

#7647 chore: enable more rules from go-critic
  .golangci.yml
  detectors/gcp/detector.go
  instrumentation/github.com/aws/aws-lambda-go/otellambda/xrayconfig/collector_test.go
  instrumentation/github.com/aws/aws-lambda-go/otellambda/xrayconfig/mock_collector_test.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/restfultest_test.go
  instrumentation/github.com/gorilla/mux/otelmux/example_test.go
  instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/internal/semconv/event_monitor.go
  instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/test/mongo_test.go
  instrumentation/go.mongodb.org/mongo-driver/v2/mongo/otelmongo/mongo_test.go
  propagators/aws/xray/propagator_test.go
  propagators/b3/b3_data_test.go
Labels: Skip Changelog

#7646 Remove the deprecated `otelgrpc.StreamClientInterceptor`
  CHANGELOG.md
  instrumentation/google.golang.org/grpc/otelgrpc/benchmark_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/go.mod
  instrumentation/google.golang.org/grpc/otelgrpc/grpc_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go
  instrumentation/google.golang.org/grpc/otelgrpc/interceptor_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/stats_handlertest_test.go
Labels: instrumentation: otelgrpc

#7660 logutil: convert standard and log attributes
  CHANGELOG.md
  bridges/otellogr/convert.go
  bridges/otellogr/convert_test.go
  bridges/otellogr/logsink_test.go
  bridges/otellogrus/convert.go
  bridges/otellogrus/convert_test.go
  bridges/otellogrus/hook_test.go
  bridges/otelslog/convert.go
  bridges/otelslog/convert_test.go
  bridges/otelzap/convert.go
  bridges/otelzap/convert_test.go
  internal/shared/logutil/convert.go.tmpl
  internal/shared/logutil/convert_test.go.tmpl
Labels: enhancement, bridge: slog, bridge: zap, bridge: logrus, bridge: logr

#7682 Use v2 AWS EC2 detector in `autodetect`
  detectors/autodetect/autodetect.go
  detectors/autodetect/go.mod
  detectors/autodetect/go.sum
Labels: Skip Changelog

#7694 chore: add detectors/aws/ec2/v2 to versions.yaml
  detectors/aws/ec2/v2/version.go
  versions.yaml
Labels: Skip Changelog

#7727 chore: enable rangeValCopy rule from go-critic
  .golangci.yml
  propagators/b3/b3_benchmark_test.go
  propagators/b3/b3_data_test.go
  samplers/probability/consistent/statistical_test.go
Labels: Skip Changelog

#7728 chore: enable nolintlint and whyNoLint rule from go-critic
  .golangci.yml
  bridges/otellogr/logsink.go
  bridges/otellogr/logsink_test.go
  bridges/otelslog/handler.go
  bridges/otelslog/handler_test.go
  bridges/otelzap/encoder.go
  detectors/aws/lambda/detector.go
  detectors/azure/azurevm/vm.go
  instrumentation/github.com/aws/aws-lambda-go/otellambda/lambda_test.go
  instrumentation/github.com/aws/aws-lambda-go/otellambda/wrapLambdaHandler.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/example_test.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconv/httpconv.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconv/util.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/restfultest_test.go
  instrumentation/github.com/gin-gonic/gin/otelgin/gin_test.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconv/httpconv.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconv/util.go
  instrumentation/github.com/gorilla/mux/otelmux/example_test.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconv/httpconv.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconv/util.go
  instrumentation/github.com/gorilla/mux/otelmux/muxtest_test.go
  instrumentation/github.com/labstack/echo/otelecho/echo_test.go
  instrumentation/github.com/labstack/echo/otelecho/echotest_test.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconv/httpconv.go
  instrumentation/github.com/labstack/echo/otelecho/internal/semconv/util.go
  instrumentation/go.mongodb.org/mongo-driver/v2/mongo/otelmongo/mongo_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/example/client/main.go
  instrumentation/google.golang.org/grpc/otelgrpc/grpc_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/internal/test/test_utils.go
  instrumentation/host/host.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconv/httpconv.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconv/util.go
  instrumentation/net/http/otelhttp/config_test.go
  instrumentation/net/http/otelhttp/handler_example_test.go
  instrumentation/net/http/otelhttp/handler_test.go
  instrumentation/net/http/otelhttp/internal/semconv/httpconv.go
  instrumentation/net/http/otelhttp/internal/semconv/util.go
  instrumentation/net/http/otelhttp/transport_test.go
  instrumentation/runtime/internal/deprecatedruntime/runtime.go
  instrumentation/runtime/internal/x/x_test.go
  instrumentation/runtime/runtime.go
  internal/shared/semconv/httpconv.go.tmpl
  internal/shared/semconv/util.go.tmpl
  otelconf/v0.2.0/metric.go
  otelconf/v0.3.0/metric.go
  samplers/jaegerremote/sampler_remote.go
  samplers/probability/consistent/base2.go
  samplers/probability/consistent/sampler.go
  samplers/probability/consistent/tracestate.go
  zpages/templates.go
Labels: Skip Changelog
