Repository open-telemetry/opentelemetry-go-contrib, pull requests merged in 2025-04, with the labels that each got.

#7059 Delete `tools/should_build.sh`
  tools/should_build.sh
Labels: Skip Changelog

#7109 Remove deprecated warning
  instrumentation/github.com/labstack/echo/otelecho/test/go.mod
Labels: Skip Changelog

#7060 Move `verify_examples.sh` to `tools/verify_examples.sh`
  RELEASING.md
  tools/verify_examples.sh
Labels: Skip Changelog

#7135 Fix markdown lint issues in examples/dice/README.md
  examples/dice/README.md
Labels: Skip Changelog

#7131 Fix markdown lint issues in instrumentation/github.com/aws/aws-lambda-go/otellambda/README.md
  instrumentation/github.com/aws/aws-lambda-go/otellambda/README.md
Labels: Skip Changelog

#7132 Fix markdown lint issues in instrumentation/github.com/aws/aws-lambda-go/otellambda/xrayconfig/README.md
  instrumentation/github.com/aws/aws-lambda-go/otellambda/xrayconfig/README.md
Labels: Skip Changelog

#7122 Fix markdown lint issues in detectors/aws/lambda
  detectors/aws/lambda/README.md
Labels: Skip Changelog

#7114 Fix markdown lint issues in detectors/gcp
  detectors/gcp/README.md
Labels: Skip Changelog

#7163 Remove markdown lint issues in CHANGELOG.md
  CHANGELOG.md
Labels: Unlock Released Changelog

#7117 Fix markdownlint errors where it makes sense
  instrumentation/net/http/httptrace/otelhttptrace/example/README.md
Labels: Skip Changelog

#7157 Fix markdown lint issues in samplers/jaegerremote
  samplers/jaegerremote/README.md
Labels: Skip Changelog

#7116 otelhttp: Fix empty lines and line length limits where it makes sense
  instrumentation/net/http/otelhttp/example/README.md
Labels: Skip Changelog

#7124 feat: add lint-markdown target
  .markdownlint.yaml
  Makefile
  dependencies.Dockerfile
Labels: Skip Changelog

#7120 Fix markdownlint in otelgrpc
  instrumentation/google.golang.org/grpc/otelgrpc/example/README.md
Labels: Skip Changelog

#7074 docs: fix markdown lint in prometheus benchmarks.md file
  bridges/prometheus/BENCHMARKS.md
Labels: Skip Changelog

#7066 Remove the tools/wait.sh script
  tools/wait.sh
Labels: Skip Changelog

#7073 propagators/aws/xray: add test for Fields method
  propagators/aws/xray/propagator_test.go
Labels: Skip Changelog

#6990 style(internal/shared/semconv): Simplify request processing
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconv/httpconv.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconv/util.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconv/httpconv.go
  instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconv/util.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconv/httpconv.go
  instrumentation/github.com/gorilla/mux/otelmux/internal/semconv/util.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconv/httpconv.go
  instrumentation/net/http/httptrace/otelhttptrace/internal/semconv/util.go
  instrumentation/net/http/otelhttp/internal/semconv/httpconv.go
  instrumentation/net/http/otelhttp/internal/semconv/util.go
  internal/shared/semconv/httpconv.go.tmpl
  internal/shared/semconv/util.go.tmpl
Labels: Skip Changelog

#7123 Fix markdown lint issues in otellambda
  instrumentation/github.com/aws/aws-lambda-go/otellambda/example/README.md
Labels: Skip Changelog

#7111 Remove the get_main_pkgs.sh script
  get_main_pkgs.sh
  tools/verify_examples.sh
Labels: Skip Changelog

#7175 Fix typo in otelhttp
  instrumentation/net/http/otelhttp/labeler.go
Labels: Skip Changelog

#7118 feat: add example for otelrestful
  instrumentation/github.com/emicklei/go-restful/otelrestful/example/Dockerfile
  instrumentation/github.com/emicklei/go-restful/otelrestful/example/README.md
  instrumentation/github.com/emicklei/go-restful/otelrestful/example/docker-compose.yml
  instrumentation/github.com/emicklei/go-restful/otelrestful/example/go.mod
  instrumentation/github.com/emicklei/go-restful/otelrestful/example/go.sum
  instrumentation/github.com/emicklei/go-restful/otelrestful/example_test.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/go.mod
  instrumentation/github.com/emicklei/go-restful/otelrestful/go.sum
  instrumentation/github.com/emicklei/go-restful/otelrestful/test/go.sum
Labels: Skip Changelog

#7216 fix(otelgin): use standard library context instead of x/net/context
  instrumentation/github.com/gin-gonic/gin/otelgin/test/gin_test.go
  instrumentation/github.com/gin-gonic/gin/otelgin/test/go.mod
Labels: Skip Changelog

#7227 otelconf: replace gopkg.in/yaml.v3 with sigs.k8s.io/yaml
  otelconf/go.mod
  otelconf/go.sum
  otelconf/v0.2.0/config.go
  otelconf/v0.3.0/config.go
Labels: Skip Changelog

#6951 otelrestful: use semconv package for request attributes and span status
  instrumentation/github.com/emicklei/go-restful/otelrestful/restful.go
  instrumentation/github.com/emicklei/go-restful/otelrestful/test/restful_test.go
Labels: Skip Changelog

#7198 otelslog: set SeverityText on log records
  CHANGELOG.md
  bridges/otelslog/handler.go
  bridges/otelslog/handler_test.go
Labels: enhancement, bridge: slog

#7238 otelgin: add @flc1125 as a code owner
  CODEOWNERS
Labels: Skip Changelog

#7242 Add @prestonvasquez as codeowner of mongo
  CODEOWNERS
Labels: Skip Changelog

#7184 Test aws xray extract
  propagators/aws/xray/propagator_test.go
Labels: Skip Changelog

#7271 Refactor `otelgrpc` to not use control parameters
  instrumentation/google.golang.org/grpc/otelgrpc/config.go
  instrumentation/google.golang.org/grpc/otelgrpc/config_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go
  instrumentation/google.golang.org/grpc/otelgrpc/metadata_supplier.go
  instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go
  instrumentation/google.golang.org/grpc/otelgrpc/stats_handler_test.go
Labels: Skip Changelog, instrumentation: otelgrpc

#7270 Upgrade semantic conventions in `otelgrpc` from `v1.17.0` to `v1.30.0`
  CHANGELOG.md
  instrumentation/google.golang.org/grpc/otelgrpc/config.go
  instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go
  instrumentation/google.golang.org/grpc/otelgrpc/internal/parse.go
  instrumentation/google.golang.org/grpc/otelgrpc/internal/parse_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/semconv.go
  instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/grpc_stats_handler_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/grpc_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/interceptor_test.go
  instrumentation/google.golang.org/grpc/otelgrpc/test/stats_handler_test.go
Labels: instrumentation: otelgrpc
